<?php

namespace Modules\Album\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Modules\MediaManager\Entities\File;

class Album extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'description', 'status','created_by'];
    protected $table = 'albums';

    public function files (){
        return $this->hasMany(File::class, 'album_id', 'id');
    }
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::saving(function ($model){
            $model->status = $model->status ?? 1;
            if (auth()->user())
            {
                $model->created_by = auth()->user()->id;
            }
        });
    }

    protected $casts = [
        'status' => 'boolean',
        'created_at' => 'date:Y-m-d'
    ];
    protected $appends = [
        'has_images',
        'images_count'
    ];
    public function getHasImagesAttribute(){
        return $this->files()->exists();
    }
    public function getImagesCountAttribute(){
        return $this->files()->count();
    }



    protected static function newFactory()
    {
        return \Modules\Album\Database\factories\AlbumFactory::new();
    }
}
