<?php

namespace Modules\MediaManager\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class File extends Model
{
    use HasFactory;

    protected $table = 'files';
    protected $fillable = [
        'name',
        'type',
        'url',
        'status',
        'album_id',
        'uploaded_by',
    ];
    public function album(){
        return $this->belongsTo(File::class, 'album_id', 'id');
    }
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::saving(function ($model){
            $model->status = $model->status ?? 1;
            if (auth()->user())
            {
                $model->uploaded_by = auth()->user()->id;
            }
        });
    }

    protected $casts = [
        'status' => 'boolean',
        'created_at' => 'date:Y-m-d'
    ];

    protected static function newFactory()
    {
        return \Modules\MediaManager\Database\factories\FileFactory::new();
    }
}
